### ISSUE TITLE
Missing or mutilevel grains break rendering

### ISSUE THREAD

**Issue by mchugh19** [carlpett/salt-vault#12]
By default the master will checkout a token with a vault policy for all salt minions as well as a single minion. But for the case where you have multiple clusters of machines with different roles, you may want to create a policy for the environment of each cluster and/or a specific role within that cluster. In our environment that means:

```
policies:
  - saltstack/minions
  - saltstack/minion/{minion}
  - saltstack/minions/{grains[ec2_tags:Environment]}/{grains[ec2_roles]}
```

In that last example, if a host doesn't have an ec2_roles grain, the mapping code crashes. It is also unable to deal with evaluating sub grains in the ec2_tags:Environment case.

**Comment by carlpett** [comment]
Aha, good catch. I'll add some error handling there. 

For the nested grains, it gets a bit tricky - that is actually just a salt helper syntax, which is also configurable, I believe. So it might be hard to implement correctly. But since it is just nested dictionaries, you can use this syntax (although it is less compact): 
`{grains[ec2_tags][Environment]}`

**Comment by mchugh19** [comment]
Super! I'd expect that a missing grain gets mapped to a "missing!" or some not likely to be already used string.

For the nested grains, if that syntax works, that's great.

**Comment by carlpett** [comment]
Hm, I'm a bit wary of assigning a policy which "should never exist". Those things tend to bite back eventually ;)

Just pushed a PR, #13, which logs an error. Are there cases where this is insufficient?

**Comment by mchugh19** [comment]
Works for me

**Comment by mchugh19** [comment]
This came back after the tokenization code. 

With a policy like: `saltstack/minion/{grains[ec2_tags][Environment]}/{grains[ec2_roles]}` where Environment is undefined

```
 salt `hostname -f` vault.read_secret secret/salt-master/jenkins
  salt-master:
    ERROR: {'error': "'Environment'"}
```

**Comment by carlpett** [comment]
Hm, but `ec2_tags` is defined? I'm having problems reproducing this, but I'll add a few test cases and see if I can catch it.

**Comment by carlpett** [comment]
Could you share those grains? I've tested with this, and it looks fine here:

```yaml
ec2_tags:
  Not-Environment: unit-test
ec2_roles:
  - test-runner
  - hamster
```

But maybe I'm using the wrong types or something?

**Comment by mchugh19** [comment]
Here's the reported error:
```
Exception occurred in runner vault.show_policies: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/var/cache/salt/master/extmods/runners/vault.py", line 50, in show_policies
    return _get_policies(minion_id, config)
  File "/var/cache/salt/master/extmods/runners/vault.py", line 77, in _get_policies
    for expanded_pattern in _expand_pattern_lists(pattern, **mappings):
  File "/var/cache/salt/master/extmods/runners/vault.py", line 113, in _expand_pattern_lists
    (value, _) = f.get_field(field_name, None, mappings)
  File "/usr/lib64/python2.7/string.py", line 640, in get_field
    obj = obj[i]
KeyError: 'Environment'
```

From the policy:
```
saltstack/minion/{grains[ec2_tags][Environment]}/{grains[ec2_roles]}
```

For a host that does have an ec2_tags grain, but not an ec2_tags:Environment grain. 
```
ec2_tags:
        ----------
        Name:
            SaltMaster
        Roles:
            SaltMaster
        aws:cloudformation:stack-name:
            Saltstack-Master
        cost_allocation:
            Saltstack
```


If the above policy is removed from the list, vault.show_policies is then able to render properly
```
# salt-run vault.show_policies $(hostname -f)
- saltstack/minions
- saltstack/minion/ip-10-241-208-27.ec2.internal
- saltstack/minion/roles/SaltMaster
```

**Comment by mchugh19** [comment]
Argh! Nevermind. Once again, I had an older checkout. Current master doesn't have this issue. 

Thanks again!
