### ISSUE TITLE
question: salt-vault and pillar

### ISSUE THREAD

**Issue by zerthimon** [carlpett/salt-vault#19]
Can I use stuff like that in pillar ?
```
env:
  password: {{ salt['vault'].read_secret('secret/my/secret') }}
```

Which policy would apply when such template is processed by a minion, a minion's policy or salt-master's policy ?

**Comment by carlpett** [comment]
Yes, that works (but do note that you will get a dictionary back, if you want to read a specific field from that dictionary, you can call it like this instead: `salt['vault'].read_secret('secret/my/secret','some_field')`).

The correct policy will be used for each minion when rendering their pillars.

**Comment by zerthimon** [comment]
Cool, @carlpett thanks for answering.
Closing
