### ISSUE TITLE
Master token policy

### ISSUE THREAD

**Issue by rcallphin** [carlpett/salt-vault#25]
Hi @carlpett, 

I know this repo is deprecated as it's merged upstream.  But I have a quick question maybe you can help me with? 

What is the desired policy for the master token?  

I'm seeing some weird behavior right now where if the minion does not match any of the defined polices then the token that that master creates is just a duplicate of its only access. 

Example:

vault:
    .....
    policies:
        - salt_{grains[roles]}

The minion that has a role in its grins data set is working fine where the master creates a token (salt_web) and then reads the secret.
The minion that does not have a role set in its grains I would expect to fail, however in my vault logs I see the master creating a token with the same policies as the master token and then reading the secret. So it never steps down it's privileges. 

What am I missing here?

**Comment by carlpett** [comment]
Hi,
Sorry for missing this! Not keeping close track of this repo since (as you mention) maintenance is upstream now. Anyway, I saw there was an issue there, so I'll respond in that one instead!

**Comment by zloyded** [comment]
`salt -v 'one_backend' vault.read_secret secret/otherbakend/stage/redis`
in logs
`Could not resolve policy pattern salt_{grains[roles]}`
but data was compiled as requested
